# Generated by Django 2.2.6 on 2019-10-22 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_lista', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
    ]
