# Generated by Django 2.2.6 on 2019-10-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_lista', '0002_auto_20191022_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
